//! Generated Unicode block classification functions (upstream xmlunicode.c).
//!
//! Each `xmlUCSIs<Block>(int code)` returns 1 when `code` falls inside
//! the Unicode block's inclusive range set, 0 otherwise — faithful to
//! upstream's inline range checks.
//!
//! Generated by tools/abi/gen_ucs_blocks.py from the oracle archaeology
//! tree (libxml2-2.13.0/xmlunicode.c); do not hand-edit.

use std::os::raw::c_int;

#[inline]
fn in_ranges(code: c_int, ranges: &[(u32, u32)]) -> c_int {
    for &(lo, hi) in ranges {
        if (code as u32) >= lo && (code as u32) <= hi {
            return 1;
        }
    }
    0
}

/// Upstream xmlunicode.c `xmlUCSIsAegeanNumbers` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsAegeanNumbers(code: c_int) -> c_int {
    in_ranges(code, &[(65792, 65855)])
}

/// Upstream xmlunicode.c `xmlUCSIsAlphabeticPresentationForms` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsAlphabeticPresentationForms(code: c_int) -> c_int {
    in_ranges(code, &[(64256, 64335)])
}

/// Upstream xmlunicode.c `xmlUCSIsArabic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsArabic(code: c_int) -> c_int {
    in_ranges(code, &[(1536, 1791)])
}

/// Upstream xmlunicode.c `xmlUCSIsArabicPresentationFormsA` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsArabicPresentationFormsA(code: c_int) -> c_int {
    in_ranges(code, &[(64336, 65023)])
}

/// Upstream xmlunicode.c `xmlUCSIsArabicPresentationFormsB` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsArabicPresentationFormsB(code: c_int) -> c_int {
    in_ranges(code, &[(65136, 65279)])
}

/// Upstream xmlunicode.c `xmlUCSIsArmenian` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsArmenian(code: c_int) -> c_int {
    in_ranges(code, &[(1328, 1423)])
}

/// Upstream xmlunicode.c `xmlUCSIsArrows` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsArrows(code: c_int) -> c_int {
    in_ranges(code, &[(8592, 8703)])
}

/// Upstream xmlunicode.c `xmlUCSIsBasicLatin` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBasicLatin(code: c_int) -> c_int {
    in_ranges(code, &[(0, 127)])
}

/// Upstream xmlunicode.c `xmlUCSIsBengali` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBengali(code: c_int) -> c_int {
    in_ranges(code, &[(2432, 2559)])
}

/// Upstream xmlunicode.c `xmlUCSIsBlockElements` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBlockElements(code: c_int) -> c_int {
    in_ranges(code, &[(9600, 9631)])
}

/// Upstream xmlunicode.c `xmlUCSIsBopomofo` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBopomofo(code: c_int) -> c_int {
    in_ranges(code, &[(12544, 12591)])
}

/// Upstream xmlunicode.c `xmlUCSIsBopomofoExtended` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBopomofoExtended(code: c_int) -> c_int {
    in_ranges(code, &[(12704, 12735)])
}

/// Upstream xmlunicode.c `xmlUCSIsBoxDrawing` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBoxDrawing(code: c_int) -> c_int {
    in_ranges(code, &[(9472, 9599)])
}

/// Upstream xmlunicode.c `xmlUCSIsBraillePatterns` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBraillePatterns(code: c_int) -> c_int {
    in_ranges(code, &[(10240, 10495)])
}

/// Upstream xmlunicode.c `xmlUCSIsBuhid` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsBuhid(code: c_int) -> c_int {
    in_ranges(code, &[(5952, 5983)])
}

/// Upstream xmlunicode.c `xmlUCSIsByzantineMusicalSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsByzantineMusicalSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(118784, 119039)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKCompatibility` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKCompatibility(code: c_int) -> c_int {
    in_ranges(code, &[(13056, 13311)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKCompatibilityForms` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKCompatibilityForms(code: c_int) -> c_int {
    in_ranges(code, &[(65072, 65103)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKCompatibilityIdeographs` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKCompatibilityIdeographs(code: c_int) -> c_int {
    in_ranges(code, &[(63744, 64255)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKCompatibilityIdeographsSupplement` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKCompatibilityIdeographsSupplement(code: c_int) -> c_int {
    in_ranges(code, &[(194560, 195103)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKRadicalsSupplement` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKRadicalsSupplement(code: c_int) -> c_int {
    in_ranges(code, &[(11904, 12031)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKSymbolsandPunctuation` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKSymbolsandPunctuation(code: c_int) -> c_int {
    in_ranges(code, &[(12288, 12351)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKUnifiedIdeographs` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKUnifiedIdeographs(code: c_int) -> c_int {
    in_ranges(code, &[(19968, 40959)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKUnifiedIdeographsExtensionA` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKUnifiedIdeographsExtensionA(code: c_int) -> c_int {
    in_ranges(code, &[(13312, 19903)])
}

/// Upstream xmlunicode.c `xmlUCSIsCJKUnifiedIdeographsExtensionB` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCJKUnifiedIdeographsExtensionB(code: c_int) -> c_int {
    in_ranges(code, &[(131072, 173791)])
}

/// Upstream xmlunicode.c `xmlUCSIsCherokee` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCherokee(code: c_int) -> c_int {
    in_ranges(code, &[(5024, 5119)])
}

/// Upstream xmlunicode.c `xmlUCSIsCombiningDiacriticalMarks` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCombiningDiacriticalMarks(code: c_int) -> c_int {
    in_ranges(code, &[(768, 879)])
}

/// Upstream xmlunicode.c `xmlUCSIsCombiningDiacriticalMarksforSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCombiningDiacriticalMarksforSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(8400, 8447)])
}

/// Upstream xmlunicode.c `xmlUCSIsCombiningHalfMarks` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCombiningHalfMarks(code: c_int) -> c_int {
    in_ranges(code, &[(65056, 65071)])
}

/// Upstream xmlunicode.c `xmlUCSIsCombiningMarksforSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCombiningMarksforSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(8400, 8447)])
}

/// Upstream xmlunicode.c `xmlUCSIsControlPictures` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsControlPictures(code: c_int) -> c_int {
    in_ranges(code, &[(9216, 9279)])
}

/// Upstream xmlunicode.c `xmlUCSIsCurrencySymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCurrencySymbols(code: c_int) -> c_int {
    in_ranges(code, &[(8352, 8399)])
}

/// Upstream xmlunicode.c `xmlUCSIsCypriotSyllabary` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCypriotSyllabary(code: c_int) -> c_int {
    in_ranges(code, &[(67584, 67647)])
}

/// Upstream xmlunicode.c `xmlUCSIsCyrillic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCyrillic(code: c_int) -> c_int {
    in_ranges(code, &[(1024, 1279)])
}

/// Upstream xmlunicode.c `xmlUCSIsCyrillicSupplement` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCyrillicSupplement(code: c_int) -> c_int {
    in_ranges(code, &[(1280, 1327)])
}

/// Upstream xmlunicode.c `xmlUCSIsDeseret` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsDeseret(code: c_int) -> c_int {
    in_ranges(code, &[(66560, 66639)])
}

/// Upstream xmlunicode.c `xmlUCSIsDevanagari` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsDevanagari(code: c_int) -> c_int {
    in_ranges(code, &[(2304, 2431)])
}

/// Upstream xmlunicode.c `xmlUCSIsDingbats` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsDingbats(code: c_int) -> c_int {
    in_ranges(code, &[(9984, 10175)])
}

/// Upstream xmlunicode.c `xmlUCSIsEnclosedAlphanumerics` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsEnclosedAlphanumerics(code: c_int) -> c_int {
    in_ranges(code, &[(9312, 9471)])
}

/// Upstream xmlunicode.c `xmlUCSIsEnclosedCJKLettersandMonths` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsEnclosedCJKLettersandMonths(code: c_int) -> c_int {
    in_ranges(code, &[(12800, 13055)])
}

/// Upstream xmlunicode.c `xmlUCSIsEthiopic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsEthiopic(code: c_int) -> c_int {
    in_ranges(code, &[(4608, 4991)])
}

/// Upstream xmlunicode.c `xmlUCSIsGeneralPunctuation` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGeneralPunctuation(code: c_int) -> c_int {
    in_ranges(code, &[(8192, 8303)])
}

/// Upstream xmlunicode.c `xmlUCSIsGeometricShapes` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGeometricShapes(code: c_int) -> c_int {
    in_ranges(code, &[(9632, 9727)])
}

/// Upstream xmlunicode.c `xmlUCSIsGeorgian` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGeorgian(code: c_int) -> c_int {
    in_ranges(code, &[(4256, 4351)])
}

/// Upstream xmlunicode.c `xmlUCSIsGothic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGothic(code: c_int) -> c_int {
    in_ranges(code, &[(66352, 66383)])
}

/// Upstream xmlunicode.c `xmlUCSIsGreek` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGreek(code: c_int) -> c_int {
    in_ranges(code, &[(880, 1023)])
}

/// Upstream xmlunicode.c `xmlUCSIsGreekExtended` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGreekExtended(code: c_int) -> c_int {
    in_ranges(code, &[(7936, 8191)])
}

/// Upstream xmlunicode.c `xmlUCSIsGreekandCoptic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGreekandCoptic(code: c_int) -> c_int {
    in_ranges(code, &[(880, 1023)])
}

/// Upstream xmlunicode.c `xmlUCSIsGujarati` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGujarati(code: c_int) -> c_int {
    in_ranges(code, &[(2688, 2815)])
}

/// Upstream xmlunicode.c `xmlUCSIsGurmukhi` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsGurmukhi(code: c_int) -> c_int {
    in_ranges(code, &[(2560, 2687)])
}

/// Upstream xmlunicode.c `xmlUCSIsHalfwidthandFullwidthForms` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHalfwidthandFullwidthForms(code: c_int) -> c_int {
    in_ranges(code, &[(65280, 65519)])
}

/// Upstream xmlunicode.c `xmlUCSIsHangulCompatibilityJamo` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHangulCompatibilityJamo(code: c_int) -> c_int {
    in_ranges(code, &[(12592, 12687)])
}

/// Upstream xmlunicode.c `xmlUCSIsHangulJamo` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHangulJamo(code: c_int) -> c_int {
    in_ranges(code, &[(4352, 4607)])
}

/// Upstream xmlunicode.c `xmlUCSIsHangulSyllables` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHangulSyllables(code: c_int) -> c_int {
    in_ranges(code, &[(44032, 55215)])
}

/// Upstream xmlunicode.c `xmlUCSIsHanunoo` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHanunoo(code: c_int) -> c_int {
    in_ranges(code, &[(5920, 5951)])
}

/// Upstream xmlunicode.c `xmlUCSIsHebrew` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHebrew(code: c_int) -> c_int {
    in_ranges(code, &[(1424, 1535)])
}

/// Upstream xmlunicode.c `xmlUCSIsHighPrivateUseSurrogates` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHighPrivateUseSurrogates(code: c_int) -> c_int {
    in_ranges(code, &[(56192, 56319)])
}

/// Upstream xmlunicode.c `xmlUCSIsHighSurrogates` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHighSurrogates(code: c_int) -> c_int {
    in_ranges(code, &[(55296, 56191)])
}

/// Upstream xmlunicode.c `xmlUCSIsHiragana` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsHiragana(code: c_int) -> c_int {
    in_ranges(code, &[(12352, 12447)])
}

/// Upstream xmlunicode.c `xmlUCSIsIPAExtensions` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsIPAExtensions(code: c_int) -> c_int {
    in_ranges(code, &[(592, 687)])
}

/// Upstream xmlunicode.c `xmlUCSIsIdeographicDescriptionCharacters` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsIdeographicDescriptionCharacters(code: c_int) -> c_int {
    in_ranges(code, &[(12272, 12287)])
}

/// Upstream xmlunicode.c `xmlUCSIsKanbun` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKanbun(code: c_int) -> c_int {
    in_ranges(code, &[(12688, 12703)])
}

/// Upstream xmlunicode.c `xmlUCSIsKangxiRadicals` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKangxiRadicals(code: c_int) -> c_int {
    in_ranges(code, &[(12032, 12255)])
}

/// Upstream xmlunicode.c `xmlUCSIsKannada` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKannada(code: c_int) -> c_int {
    in_ranges(code, &[(3200, 3327)])
}

/// Upstream xmlunicode.c `xmlUCSIsKatakana` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKatakana(code: c_int) -> c_int {
    in_ranges(code, &[(12448, 12543)])
}

/// Upstream xmlunicode.c `xmlUCSIsKatakanaPhoneticExtensions` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKatakanaPhoneticExtensions(code: c_int) -> c_int {
    in_ranges(code, &[(12784, 12799)])
}

/// Upstream xmlunicode.c `xmlUCSIsKhmer` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKhmer(code: c_int) -> c_int {
    in_ranges(code, &[(6016, 6143)])
}

/// Upstream xmlunicode.c `xmlUCSIsKhmerSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsKhmerSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(6624, 6655)])
}

/// Upstream xmlunicode.c `xmlUCSIsLao` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLao(code: c_int) -> c_int {
    in_ranges(code, &[(3712, 3839)])
}

/// Upstream xmlunicode.c `xmlUCSIsLatin1Supplement` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLatin1Supplement(code: c_int) -> c_int {
    in_ranges(code, &[(128, 255)])
}

/// Upstream xmlunicode.c `xmlUCSIsLatinExtendedA` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLatinExtendedA(code: c_int) -> c_int {
    in_ranges(code, &[(256, 383)])
}

/// Upstream xmlunicode.c `xmlUCSIsLatinExtendedAdditional` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLatinExtendedAdditional(code: c_int) -> c_int {
    in_ranges(code, &[(7680, 7935)])
}

/// Upstream xmlunicode.c `xmlUCSIsLatinExtendedB` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLatinExtendedB(code: c_int) -> c_int {
    in_ranges(code, &[(384, 591)])
}

/// Upstream xmlunicode.c `xmlUCSIsLetterlikeSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLetterlikeSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(8448, 8527)])
}

/// Upstream xmlunicode.c `xmlUCSIsLimbu` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLimbu(code: c_int) -> c_int {
    in_ranges(code, &[(6400, 6479)])
}

/// Upstream xmlunicode.c `xmlUCSIsLinearBIdeograms` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLinearBIdeograms(code: c_int) -> c_int {
    in_ranges(code, &[(65664, 65791)])
}

/// Upstream xmlunicode.c `xmlUCSIsLinearBSyllabary` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLinearBSyllabary(code: c_int) -> c_int {
    in_ranges(code, &[(65536, 65663)])
}

/// Upstream xmlunicode.c `xmlUCSIsLowSurrogates` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsLowSurrogates(code: c_int) -> c_int {
    in_ranges(code, &[(56320, 57343)])
}

/// Upstream xmlunicode.c `xmlUCSIsMalayalam` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMalayalam(code: c_int) -> c_int {
    in_ranges(code, &[(3328, 3455)])
}

/// Upstream xmlunicode.c `xmlUCSIsMathematicalAlphanumericSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMathematicalAlphanumericSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(119808, 120831)])
}

/// Upstream xmlunicode.c `xmlUCSIsMathematicalOperators` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMathematicalOperators(code: c_int) -> c_int {
    in_ranges(code, &[(8704, 8959)])
}

/// Upstream xmlunicode.c `xmlUCSIsMiscellaneousMathematicalSymbolsA` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMiscellaneousMathematicalSymbolsA(code: c_int) -> c_int {
    in_ranges(code, &[(10176, 10223)])
}

/// Upstream xmlunicode.c `xmlUCSIsMiscellaneousMathematicalSymbolsB` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMiscellaneousMathematicalSymbolsB(code: c_int) -> c_int {
    in_ranges(code, &[(10624, 10751)])
}

/// Upstream xmlunicode.c `xmlUCSIsMiscellaneousSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMiscellaneousSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(9728, 9983)])
}

/// Upstream xmlunicode.c `xmlUCSIsMiscellaneousSymbolsandArrows` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMiscellaneousSymbolsandArrows(code: c_int) -> c_int {
    in_ranges(code, &[(11008, 11263)])
}

/// Upstream xmlunicode.c `xmlUCSIsMiscellaneousTechnical` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMiscellaneousTechnical(code: c_int) -> c_int {
    in_ranges(code, &[(8960, 9215)])
}

/// Upstream xmlunicode.c `xmlUCSIsMongolian` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMongolian(code: c_int) -> c_int {
    in_ranges(code, &[(6144, 6319)])
}

/// Upstream xmlunicode.c `xmlUCSIsMusicalSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMusicalSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(119040, 119295)])
}

/// Upstream xmlunicode.c `xmlUCSIsMyanmar` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsMyanmar(code: c_int) -> c_int {
    in_ranges(code, &[(4096, 4255)])
}

/// Upstream xmlunicode.c `xmlUCSIsNumberForms` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsNumberForms(code: c_int) -> c_int {
    in_ranges(code, &[(8528, 8591)])
}

/// Upstream xmlunicode.c `xmlUCSIsOgham` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsOgham(code: c_int) -> c_int {
    in_ranges(code, &[(5760, 5791)])
}

/// Upstream xmlunicode.c `xmlUCSIsOldItalic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsOldItalic(code: c_int) -> c_int {
    in_ranges(code, &[(66304, 66351)])
}

/// Upstream xmlunicode.c `xmlUCSIsOpticalCharacterRecognition` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsOpticalCharacterRecognition(code: c_int) -> c_int {
    in_ranges(code, &[(9280, 9311)])
}

/// Upstream xmlunicode.c `xmlUCSIsOriya` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsOriya(code: c_int) -> c_int {
    in_ranges(code, &[(2816, 2943)])
}

/// Upstream xmlunicode.c `xmlUCSIsOsmanya` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsOsmanya(code: c_int) -> c_int {
    in_ranges(code, &[(66688, 66735)])
}

/// Upstream xmlunicode.c `xmlUCSIsPhoneticExtensions` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsPhoneticExtensions(code: c_int) -> c_int {
    in_ranges(code, &[(7424, 7551)])
}

/// Upstream xmlunicode.c `xmlUCSIsPrivateUse` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsPrivateUse(code: c_int) -> c_int {
    in_ranges(
        code,
        &[(57344, 63743), (983040, 1048575), (1048576, 1114111)],
    )
}

/// Upstream xmlunicode.c `xmlUCSIsPrivateUseArea` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsPrivateUseArea(code: c_int) -> c_int {
    in_ranges(code, &[(57344, 63743)])
}

/// Upstream xmlunicode.c `xmlUCSIsRunic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsRunic(code: c_int) -> c_int {
    in_ranges(code, &[(5792, 5887)])
}

/// Upstream xmlunicode.c `xmlUCSIsShavian` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsShavian(code: c_int) -> c_int {
    in_ranges(code, &[(66640, 66687)])
}

/// Upstream xmlunicode.c `xmlUCSIsSinhala` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSinhala(code: c_int) -> c_int {
    in_ranges(code, &[(3456, 3583)])
}

/// Upstream xmlunicode.c `xmlUCSIsSmallFormVariants` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSmallFormVariants(code: c_int) -> c_int {
    in_ranges(code, &[(65104, 65135)])
}

/// Upstream xmlunicode.c `xmlUCSIsSpacingModifierLetters` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSpacingModifierLetters(code: c_int) -> c_int {
    in_ranges(code, &[(688, 767)])
}

/// Upstream xmlunicode.c `xmlUCSIsSpecials` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSpecials(code: c_int) -> c_int {
    in_ranges(code, &[(65520, 65535)])
}

/// Upstream xmlunicode.c `xmlUCSIsSuperscriptsandSubscripts` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSuperscriptsandSubscripts(code: c_int) -> c_int {
    in_ranges(code, &[(8304, 8351)])
}

/// Upstream xmlunicode.c `xmlUCSIsSupplementalArrowsA` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSupplementalArrowsA(code: c_int) -> c_int {
    in_ranges(code, &[(10224, 10239)])
}

/// Upstream xmlunicode.c `xmlUCSIsSupplementalArrowsB` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSupplementalArrowsB(code: c_int) -> c_int {
    in_ranges(code, &[(10496, 10623)])
}

/// Upstream xmlunicode.c `xmlUCSIsSupplementalMathematicalOperators` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSupplementalMathematicalOperators(code: c_int) -> c_int {
    in_ranges(code, &[(10752, 11007)])
}

/// Upstream xmlunicode.c `xmlUCSIsSupplementaryPrivateUseAreaA` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSupplementaryPrivateUseAreaA(code: c_int) -> c_int {
    in_ranges(code, &[(983040, 1048575)])
}

/// Upstream xmlunicode.c `xmlUCSIsSupplementaryPrivateUseAreaB` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSupplementaryPrivateUseAreaB(code: c_int) -> c_int {
    in_ranges(code, &[(1048576, 1114111)])
}

/// Upstream xmlunicode.c `xmlUCSIsSyriac` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsSyriac(code: c_int) -> c_int {
    in_ranges(code, &[(1792, 1871)])
}

/// Upstream xmlunicode.c `xmlUCSIsTagalog` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTagalog(code: c_int) -> c_int {
    in_ranges(code, &[(5888, 5919)])
}

/// Upstream xmlunicode.c `xmlUCSIsTagbanwa` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTagbanwa(code: c_int) -> c_int {
    in_ranges(code, &[(5984, 6015)])
}

/// Upstream xmlunicode.c `xmlUCSIsTags` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTags(code: c_int) -> c_int {
    in_ranges(code, &[(917504, 917631)])
}

/// Upstream xmlunicode.c `xmlUCSIsTaiLe` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTaiLe(code: c_int) -> c_int {
    in_ranges(code, &[(6480, 6527)])
}

/// Upstream xmlunicode.c `xmlUCSIsTaiXuanJingSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTaiXuanJingSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(119552, 119647)])
}

/// Upstream xmlunicode.c `xmlUCSIsTamil` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTamil(code: c_int) -> c_int {
    in_ranges(code, &[(2944, 3071)])
}

/// Upstream xmlunicode.c `xmlUCSIsTelugu` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTelugu(code: c_int) -> c_int {
    in_ranges(code, &[(3072, 3199)])
}

/// Upstream xmlunicode.c `xmlUCSIsThaana` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsThaana(code: c_int) -> c_int {
    in_ranges(code, &[(1920, 1983)])
}

/// Upstream xmlunicode.c `xmlUCSIsThai` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsThai(code: c_int) -> c_int {
    in_ranges(code, &[(3584, 3711)])
}

/// Upstream xmlunicode.c `xmlUCSIsTibetan` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsTibetan(code: c_int) -> c_int {
    in_ranges(code, &[(3840, 4095)])
}

/// Upstream xmlunicode.c `xmlUCSIsUgaritic` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsUgaritic(code: c_int) -> c_int {
    in_ranges(code, &[(66432, 66463)])
}

/// Upstream xmlunicode.c `xmlUCSIsUnifiedCanadianAboriginalSyllabics` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsUnifiedCanadianAboriginalSyllabics(code: c_int) -> c_int {
    in_ranges(code, &[(5120, 5759)])
}

/// Upstream xmlunicode.c `xmlUCSIsVariationSelectors` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsVariationSelectors(code: c_int) -> c_int {
    in_ranges(code, &[(65024, 65039)])
}

/// Upstream xmlunicode.c `xmlUCSIsVariationSelectorsSupplement` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsVariationSelectorsSupplement(code: c_int) -> c_int {
    in_ranges(code, &[(917760, 917999)])
}

/// Upstream xmlunicode.c `xmlUCSIsYiRadicals` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsYiRadicals(code: c_int) -> c_int {
    in_ranges(code, &[(42128, 42191)])
}

/// Upstream xmlunicode.c `xmlUCSIsYiSyllables` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsYiSyllables(code: c_int) -> c_int {
    in_ranges(code, &[(40960, 42127)])
}

/// Upstream xmlunicode.c `xmlUCSIsYijingHexagramSymbols` — Unicode block membership test.
#[no_mangle]
pub extern "C" fn xmlUCSIsYijingHexagramSymbols(code: c_int) -> c_int {
    in_ranges(code, &[(19904, 19967)])
}
