//! Generated Unicode category classification functions (upstream xmlunicode.c).
//!
//! Each `xmlUCSIsCatX(int code)` returns 1 when `code` belongs to the
//! Unicode general category — faithful to upstream's xmlCharInRange
//! semantics over the short/long range tables.
//!
//! Generated by tools/abi/gen_ucs_blocks.py from the oracle archaeology
//! tree (libxml2-2.13.0/xmlunicode.c); do not hand-edit.

use std::os::raw::c_int;

#[inline]
fn in_ranges(code: c_int, ranges: &[(u32, u32)]) -> c_int {
    for &(lo, hi) in ranges {
        if (code as u32) >= lo && (code as u32) <= hi {
            return 1;
        }
    }
    0
}

/// Upstream xmlunicode.c `xmlUCSIsCatC` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatC(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatCf` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatCf(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatCo` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatCo(code: c_int) -> c_int {
    in_ranges(
        code,
        &[
            (57344, 57344),
            (63743, 63743),
            (983040, 983040),
            (1048573, 1048573),
            (1048576, 1048576),
            (1114109, 1114109),
        ],
    )
}

/// Upstream xmlunicode.c `xmlUCSIsCatCs` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatCs(code: c_int) -> c_int {
    in_ranges(code, &[(55296, 55296), (57343, 57343)])
}

/// Upstream xmlunicode.c `xmlUCSIsCatL` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatL(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatLl` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatLl(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatLm` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatLm(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatLo` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatLo(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatLt` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatLt(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatLu` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatLu(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatM` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatM(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatMc` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatMc(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatMe` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatMe(code: c_int) -> c_int {
    in_ranges(code, &[(1758, 1758)])
}

/// Upstream xmlunicode.c `xmlUCSIsCatMn` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatMn(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatN` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatN(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatNd` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatNd(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatNl` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatNl(code: c_int) -> c_int {
    in_ranges(code, &[(12295, 12295), (66378, 66378)])
}

/// Upstream xmlunicode.c `xmlUCSIsCatNo` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatNo(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatP` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatP(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatPc` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPc(code: c_int) -> c_int {
    in_ranges(
        code,
        &[
            (95, 95),
            (8276, 8276),
            (12539, 12539),
            (65343, 65343),
            (65381, 65381),
        ],
    )
}

/// Upstream xmlunicode.c `xmlUCSIsCatPd` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPd(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatPe` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPe(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatPf` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPf(code: c_int) -> c_int {
    in_ranges(
        code,
        &[(187, 187), (8217, 8217), (8221, 8221), (8250, 8250)],
    )
}

/// Upstream xmlunicode.c `xmlUCSIsCatPi` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPi(code: c_int) -> c_int {
    in_ranges(
        code,
        &[(171, 171), (8216, 8216), (8223, 8223), (8249, 8249)],
    )
}

/// Upstream xmlunicode.c `xmlUCSIsCatPo` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPo(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatPs` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatPs(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatS` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatS(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatSc` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatSc(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatSk` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatSk(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatSm` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatSm(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatSo` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatSo(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatZ` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatZ(code: c_int) -> c_int {
    in_ranges(code, &[])
}

/// Upstream xmlunicode.c `xmlUCSIsCatZl` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatZl(code: c_int) -> c_int {
    in_ranges(code, &[(8232, 8232)])
}

/// Upstream xmlunicode.c `xmlUCSIsCatZp` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatZp(code: c_int) -> c_int {
    in_ranges(code, &[(8233, 8233)])
}

/// Upstream xmlunicode.c `xmlUCSIsCatZs` — Unicode general-category test.
#[no_mangle]
pub extern "C" fn xmlUCSIsCatZs(code: c_int) -> c_int {
    in_ranges(
        code,
        &[
            (32, 32),
            (160, 160),
            (5760, 5760),
            (6158, 6158),
            (8239, 8239),
            (8287, 8287),
            (12288, 12288),
        ],
    )
}
