#!/usr/bin/env python3
"""Deterministic generator for the libxml2 character-class tables (11.1-D/R-000135).

Extracts the upstream `xmlIs*` char-class tables verbatim from the archaeology
source tree's generated `codegen/ranges.inc` (libxml2 ≥2.13) and emits
`src/xml/unicode_tables.rs` — the exported C data globals:

    xmlIsPubidChar_tab[256]
    xmlIsBaseCharGroup / xmlIsCharGroup / xmlIsCombiningGroup
    xmlIsDigitGroup / xmlIsExtenderGroup / xmlIsIdeographicGroup

The generated file is committed; regeneration must be byte-identical
(deterministic generator rule). Run:

    python3 tools/archaeology/gen_chvalid_tables.py [ranges.inc path]

The default path resolves the newest libxml2 archaeology tree containing the
file. Usage is recorded in the generated header (input hash + source path).
"""

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INC = None
for cand in sorted((ROOT / "oracle/historical/src").glob("libxml2-*/codegen/ranges.inc")):
    DEFAULT_INC = cand  # lexicographic max = newest version
if DEFAULT_INC is None:
    sys.exit("no ranges.inc found under oracle/historical/src/libxml2-*/")


def parse_inc(path: Path):
    text = path.read_text()
    # xmlIsPubidChar_tab[256] = { 0x00, ... };
    m = re.search(r"xmlIsPubidChar_tab\[256\]\s*=\s*\{(.*?)\};", text, re.S)
    if not m:
        sys.exit("xmlIsPubidChar_tab not found in " + str(path))
    pubid = [int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1))]
    if len(pubid) != 256:
        sys.exit(f"pubid table has {len(pubid)} entries, expected 256")

    # static const xmlChSRange xmlIs<Name>_srng[] = {{0x.., 0x..}, ...};
    tables = {}
    for m in re.finditer(
        r"static const xmlChSRange (\w+)\[\]\s*=\s*\{(.*?)\};", text, re.S
    ):
        name = m.group(1)
        pairs = re.findall(r"\{0x([0-9a-fA-F]+),\s*0x([0-9a-fA-F]+)\}", m.group(2))
        tables[name] = [(int(a, 16), int(b, 16)) for a, b in pairs]
    for m in re.finditer(
        r"static const xmlChLRange (\w+)\[\]\s*=\s*\{(.*?)\};", text, re.S
    ):
        name = m.group(1)
        pairs = re.findall(r"\{0x([0-9a-fA-F]+),\s*0x([0-9a-fA-F]+)\}", m.group(2))
        tables[name] = [(int(a, 16), int(b, 16)) for a, b in pairs]

    # const xmlChRangeGroup xmlIsBaseCharGroup = {197,0,xmlIsBaseChar_srng,NULL};
    groups = []
    for m in re.finditer(
        r"const xmlChRangeGroup (\w+)\s*=\s*\{(\d+),(\d+),(\w+|NULL),(\w+|NULL)\};",
        text,
    ):
        gname, nshort, nlong, srng, lrng = m.groups()
        nshort, nlong = int(nshort), int(nlong)
        sr = tables.get(srng, [])
        lr = tables.get(lrng, [])
        # verify the handwritten counts against the parsed arrays
        if len(sr) != nshort:
            sys.exit(f"{gname}: srng count {len(sr)} != declared {nshort}")
        if len(lr) != nlong:
            sys.exit(f"{gname}: lrng count {len(lr)} != declared {nlong}")
        groups.append((gname, sr, lr))
    return pubid, groups, text


def fmt_table(name, pairs, ty):
    lines = [f"/// Upstream `{name}[]` — {len(pairs)} {ty} ranges (2.15.0)."]
    lines.append(f"#[no_mangle]")
    lines.append(f"pub static {name}: [{ty}; {len(pairs)}] = [")
    row = []
    for low, high in pairs:
        row.append(f"    {ty} {{ low: 0x{low:x}, high: 0x{high:x} }},")
        if len(row) == 4:
            lines.extend(row)
            row = []
    lines.extend(row)
    lines.append("];")
    return "\n".join(lines)


def main():
    inc = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_INC
    inc = inc.resolve()
    pubid, groups, text = parse_inc(inc)
    src_hash = hashlib.sha256(text.encode()).hexdigest()
    rel = inc.relative_to(ROOT)

    out = []
    out.append("// GENERATED by tools/archaeology/gen_chvalid_tables.py — do not hand-edit.")
    out.append("//")
    out.append("// Verbatim extraction of the upstream libxml2 character-class")
    out.append("// tables (exported C data globals, chvalid.h / codegen/ranges.inc).")
    out.append("// Data provenance: " + str(rel))
    out.append(f"// ranges.inc sha256: {src_hash}")
    out.append("//")
    out.append("// # SAFETY")
    out.append("//")
    out.append("// The tables are immutable const data; the #[no_mangle] exports")
    out.append("// match the upstream `const xmlChRangeGroup xmlIs*Group` and")
    out.append("// `const unsigned char xmlIsPubidChar_tab[256]` symbols (data ABI).")
    out.append("")
    out.append("use crate::abi::structs::{xmlChLRange, xmlChRangeGroup, xmlChSRange};")
    out.append("")
    out.append("/// Upstream `const unsigned char xmlIsPubidChar_tab[256]`.")
    out.append("#[no_mangle]")
    out.append("pub static xmlIsPubidChar_tab: [u8; 256] = [")
    for i in range(0, 256, 16):
        chunk = ", ".join(f"0x{b:02x}" for b in pubid[i : i + 16])
        out.append(f"    {chunk},")
    out.append("];")
    out.append("")
    for gname, sr, lr in groups:
        sname = gname.replace("Group", "_srng")
        if sr:
            out.append(fmt_table(sname, sr, "xmlChSRange"))
            out.append("")
        if lr:
            out.append(fmt_table(gname.replace("Group", "_lrng"), lr, "xmlChLRange"))
            out.append("")
        out.append(f"/// Upstream `const xmlChRangeGroup {gname}`.")
        out.append("#[no_mangle]")
        sr_ref = f"&{sname} as *const xmlChSRange" if sr else "core::ptr::null()"
        lr_ref = f"&{gname.replace('Group', '_lrng')} as *const xmlChLRange" if lr else "core::ptr::null()"
        out.append(f"pub static {gname}: xmlChRangeGroup = xmlChRangeGroup {{")
        out.append(f"    nbShortRange: {len(sr)},")
        out.append(f"    nbLongRange: {len(lr)},")
        out.append(f"    shortRange: {sr_ref},")
        out.append(f"    longRange: {lr_ref},")
        out.append("};")
        out.append("")
    dst = ROOT / "src/xml/unicode_tables.rs"
    dst.write_text("\n".join(out) + "\n")
    print(f"wrote {dst.relative_to(ROOT)} (pubid=256, groups={len(groups)})")
    print(f"input: {rel} sha256={src_hash}")


if __name__ == "__main__":
    main()
