#!/usr/bin/env python3
"""ABI-FUNCTION-SIGNATURE court (11.1-Z.2; hardened 11.1-Z.3) — three-way C
function-prototype mirror.

For every externally relevant function the court proves the triangle:

    oracle Clang C prototype            (system headers, clang AST)
              ↕  (must match at SOURCE + MACHINE-ABI level)
    candidate installed C prototype     (include/, clang AST)
              ↕  (must match at MACHINE-ABI level)
    actual Rust extern "C" signature    (src/, extracted from source)

Two fingerprints are measured per symbol (11.1-Z.3):

    SOURCE_PROTOTYPE_FINGERPRINT
        canonical/desugared base type, pointer depth, const/restrict where
        source-visible, typedef identity where important, FULL function-pointer
        signature (not just "fnptr"), variadic, argument count, return type,
        calling convention — compared between oracle and candidate headers.

    MACHINE_ABI_FINGERPRINT
        ABI class (int/float/ptr/fnptr/void/struct), width, SIGNEDNESS
        (int vs uint vs long vs ulong vs size_t/usize ...), pointer depth,
        struct-by-value identity, callback ABI, variadic — compared between
        oracle/candidate headers AND candidate headers/Rust implementation
        (size_t ≡ usize, c_long ≡ long, ... at the machine level).

The x86-64 assembly variadic shims (xmlGenericError / xsltGenericError
default printers, xmlStrPrintf, xsltTransformError, the four legacy SAX v1
handlers, and the 13 xmlTextWriterWriteFormat* shims generated by the
vfmt_shim!/fmt_stub! macros, R-000161/R-000176) have C-variadic prototypes
but Rust signatures that are the documented shim form; they are CLASSIFIED
in ASM_SHIMS / GENERATED_MACRO_SHIMS, never silently skipped.

Fail-closed + oracle-isolated (11.1-Z.3):

  - the oracle plane compiles with ONLY system include paths
    (/usr/include/libxml2 + the default system paths) and the candidate plane
    with ONLY repo include paths — the two universes are fully separated;
  - every resolved include is recorded (`clang -H`) and cross-contamination
    (an oracle parse resolving a repo header, or a candidate parse resolving
    a system project header) is a finding;
  - a header clang cannot parse is a finding (never silently dropped);
  - a function declared by the candidate header without a measured Rust
    `extern "C" fn` is a finding unless it has a named disposition
    (DATA / ASM shim / macro-generated shim / candidate-header auxiliary);
  - every declaration is accounted: silent_omissions must be 0.

This is the function-level equivalent of the struct-mirror court (RUST-MIRROR-
ABI): a signature mismatch here means a C caller following the installed
header passes arguments/expects a return that the Rust implementation
misreads — the xmlGcMemSetup class of bug (11.1-Z.2, R-000176).

Usage:
  function_signature_court.py            # run the court, write a receipt
  function_signature_court.py --report   # print every finding in detail
"""
import argparse
import datetime
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "src")
INCLUDE = os.path.join(ROOT, "include")
RECEIPTS = os.path.join(ROOT, "courts", "receipts", "phase-11")

ORACLE_HEADER_DIRS = ["/usr/include/libxml2/libxml",
                      "/usr/include/libxslt", "/usr/include/libexslt"]
CAND_HEADER_DIRS = [os.path.join(INCLUDE, "libxml"),
                    os.path.join(INCLUDE, "libxslt"),
                    os.path.join(INCLUDE, "libexslt")]

# Fully separated compilation environments (11.1-Z.3). The oracle plane must
# resolve `<libxml/...>` from /usr/include/libxml2 ONLY and the candidate
# plane from the repo `include/` ONLY. Cross-boundary resolution is a finding.
ORACLE_INCLUDE_PATHS = ["/usr/include/libxml2"]
CAND_INCLUDE_PATHS = [INCLUDE]
ORACLE_FORBIDDEN_ROOTS = [os.path.realpath(INCLUDE)]
CAND_FORBIDDEN_ROOTS = [os.path.realpath("/usr/include/libxml2"),
                        os.path.realpath("/usr/include/libxslt"),
                        os.path.realpath("/usr/include/libexslt")]

# ── x86-64 variadic asm shims: C prototype is variadic; the Rust signature is
# the documented shim form (R-000161). Measured in src/, classified not compared.
ASM_SHIMS = {
    "xmlGenericErrorDefaultFunc",
    "xsltGenericErrorDefaultFunc",
    "xmlStrPrintf",
    "xsltTransformError",
    "xmlParserError",
    "xmlParserWarning",
    "xmlParserValidityError",
    "xmlParserValidityWarning",
}

# Oracle-header internal indirection names (globals.h DLL-import scheme):
# `__xmlGenericError` etc. are the library-internal backing symbols behind the
# macro-aliased public globals; the candidate exports the clean public names
# only. Classified, not flagged.
ORACLE_INTERNAL_GLOBALS = {
    "__xmlGenericError",
    "__xmlGenericErrorContext",
    "__xmlLastError",
    "__xmlOutputBufferCreateFilename",
    "__xmlOutputBufferCreateFilenameValue",
    "__xmlParserInputBufferCreateFilename",
    "__xmlParserInputBufferCreateFilenameValue",
    "__xmlStructuredError",
    "__xmlStructuredErrorContext",
    # globals.h DLL-import backing variables behind the macro-aliased public
    # globals (11.1-Z.3 signature court: clang renders them as function-like
    # decls; they are DATA variables, classified like the __xml* above)
    "__xmlDeregisterNodeDefaultValue",
    "__xmlDoValidityCheckingDefaultValue",
    "__xmlGetWarningsDefaultValue",
    "__xmlIndentTreeOutput",
    "__xmlKeepBlanksDefaultValue",
    "__xmlLineNumbersDefaultValue",
    "__xmlLoadExtDtdDefaultValue",
    "__xmlPedanticParserDefaultValue",
    "__xmlRegisterNodeDefaultValue",
    "__xmlSaveNoEmptyTags",
    "__xmlSubstituteEntitiesDefaultValue",
    "__xmlTreeIndentString",
}

# Oracle-header declarations the oracle DSO itself does not export: verified
# with `nm -D` against the system DSO, so they are NOT candidate obligations.
# 11.1-Z.3: reclassified from the old "residual R-000176" label (R-000176 is
# FIXED) to HEADER_DECLARED_ORACLE_DSO_ABSENT.
HEADER_DECLARED_ORACLE_DSO_ABSENT = {
    "xslHandleDebugger":
        "declared in the oracle transform.h (XSLT debugger hook) but NOT "
        "exported by the system libxslt.so.1 (verified: nm -D has no such "
        "symbol, only xsltGetDebuggerStatus); current-oracle requirement: "
        "N/A — not a candidate obligation; feature: XSLT debugger",
    "xsltCleanupSourceDoc":
        "declared in the oracle internal header transformInternals.h but NOT "
        "exported by the system libxslt.so.1 (verified: nm -D has no such "
        "symbol); current-oracle requirement: N/A — not a candidate "
        "obligation",
}

# Candidate-only auxiliary headers (vendored upstream trio compatibility
# header): the oracle 1.1.45 does not ship trio.h at all (trio was removed
# upstream), and the header-compile court's declared-exported check does not
# cover trio's non-XMLPUBFUN declarations. Functions declared there are not
# part of the drop-in parity surface and are not implemented/exported.
CANDIDATE_HEADER_AUXILIARY = ("trio_",)

# Oracle headers that are not self-contained (upstream includes them only
# after a prerequisite header; the candidate's header-compile court requires
# self-containment of the CANDIDATE headers, which all pass). The old court
# silently dropped these two — a fail-open omission this court must not
# repeat. They are parsed through a wrapper that includes the prerequisite,
# and only declarations located IN the target header are kept (their
# declaring file is recorded and filtered exactly).
ORACLE_HEADER_PREREQS = {
    "namespaces.h": ["<libxslt/xsltInternals.h>"],
    "transformInternals.h": ["<libxml/tree.h>"],
}

# Exports that are DATA (function-pointer variables / globals), not functions —
# the function-signature plane does not apply to the Rust `static`.
DATA_EXPORTS = {
    "xmlFree", "xmlMalloc", "xmlMallocAtomic", "xmlRealloc", "xmlMemStrdup",
    "xmlParserVersion", "xmlStringText", "xmlStringTextNoenc", "xmlStringComment",
    "xmlStringTextLen", "xmlEntityValue", "xmlBufferAllocScheme", "xmlDefaultBufferSize",
    "xmlGenericError", "xmlGenericErrorContext", "xmlStructuredError", "xmlStructuredErrorContext",
    "xmlRegisterNodeDefaultValue", "xmlDeregisterNodeDefaultValue", "xmlTreeIndentString",
    "xmlSaveNoEmptyTags", "xmlIndentTreeOutput", "xmlTreeDebug", "xmlSaveDebug",
    "xmlDoValidityCheckingDefaultValue", "xmlPedanticParserDefaultValue",
    "xmlLineNumbersDefaultValue", "xmlLoadExtDtdDefaultValue", "xmlKeepBlanksDefaultValue",
    "xmlSubstituteEntitiesDefaultValue", "xmlDebugEntities", "xmlParserDebugEntities",
    "xmlOldXMLWDcompatibility", "xmlDefaultSAXHandler", "xmlDefaultSAXLocator",
    "xmlLastError", "xmlCharEncodingHandlers", "xmlParserInputBufferCreateFilenameDefault",
    "xmlOutputBufferCreateFilenameDefault", "xmlXPathNAN", "xmlXPathPINF", "xmlXPathNINF",
    "xmlXPathNaN", "xmlXPathPInf", "xmlXPathNInf",
    "xsltGenericDebug", "xsltGenericDebugContext", "xsltGenericError", "xsltGenericErrorContext",
    "xsltLibxmlVersion", "xsltLibxsltVersion", "xsltEngineVersion", "xsltDocDefaultLoader",
    "xsltExtMarker", "xslDebugStatus",
    "exsltLibraryVersion", "exsltLibexsltVersion", "exsltLibxmlVersion", "exsltLibxsltVersion",
}


# ── type normalization helpers ──────────────────────────────────────────────

# C integer/float spelling -> canonical source token
C_BASE_NORM = {
    "void": "void",
    "int": "int", "unsigned int": "uint",
    "long": "long", "unsigned long": "ulong",
    "long long": "longlong", "unsigned long long": "ulonglong",
    "short": "short", "unsigned short": "ushort",
    "char": "char", "signed char": "schar", "unsigned char": "uchar",
    "size_t": "size_t", "ssize_t": "ssize_t", "ptrdiff_t": "ptrdiff_t",
    "intptr_t": "intptr_t", "uintptr_t": "uintptr_t",
    "float": "float", "double": "double",
}

# C base -> MACHINE_ABI_FINGERPRINT (class, width, signed)
def c_base_abi(t):
    return {
        "void": ("void", 0, None),
        "int": ("int", 32, True), "unsigned int": ("int", 32, False),
        "long": ("int", 64, True), "unsigned long": ("int", 64, False),
        "long long": ("int", 64, True), "unsigned long long": ("int", 64, False),
        "short": ("int", 16, True), "unsigned short": ("int", 16, False),
        "char": ("int", 8, True), "signed char": ("int", 8, True),
        "unsigned char": ("int", 8, False),
        "size_t": ("int", 64, False), "ssize_t": ("int", 64, True),
        "ptrdiff_t": ("int", 64, True),
        "intptr_t": ("int", 64, True), "uintptr_t": ("int", 64, False),
        "float": ("float", 32, None), "double": ("float", 64, None),
    }.get(t, None)


def is_fnptr_text(u):
    """True if a desugared typedef text is a function-pointer type."""
    return "(" in u and "*" in u and re.search(r"\)\s*\(", u) is not None


FNPTR_RE = re.compile(r"^(.*?)\(\s*\*(?:\s+[A-Za-z_]\w*)?\s*\)\s*\((.*)\)\s*$")


def split_params(sig_text):
    """Split a Rust/C parameter list at top-level commas (nesting-aware;
    the `>` of a `->` arrow is not a closing bracket)."""
    parts, depth, cur, prev = [], 0, [], ""
    for ch in sig_text:
        if ch in "<([":
            depth += 1
        elif ch in ">)]" and not (ch == ">" and prev == "-"):
            depth -= 1
        if ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
        prev = ch
    if "".join(cur).strip():
        parts.append("".join(cur).strip())
    return [p for p in parts if p]


def split_c_pointer(t, sigs):
    """Split a C type text into (pointee_text, pointer_depth, pointer_quals).

    Follows pointer-typedef chains fully (`htmlDocPtr` -> `xmlDocPtr` ->
    `xmlDoc *` -> pointee `xmlDoc`, depth 1) and handles pointer-typedef
    pointees under stars (`xmlNsPtr *` == `xmlNs **` -> depth 2).
    Function-pointer typedefs must be handled by the caller BEFORE this
    (they contain `*`)."""
    tokens = t.replace("*", " * ").split()
    depth = 0
    pquals = []
    i = len(tokens) - 1
    while i >= 0:
        tok = tokens[i]
        if tok == "*":
            depth += 1
            i -= 1
        elif tok in ("const", "restrict", "volatile"):
            pquals.insert(0, tok)
            i -= 1
        else:
            break
    pointee = tokens[: i + 1]
    text = " ".join(pointee)
    # a pointer-typedef anywhere in the pointee position: `xmlNodePtr` (no
    # stars) or `xmlNsPtr *` (stars + pointer-typedef pointee). Walk the
    # typedef chain until a non-pointer base remains.
    while True:
        quals = [tk for tk in text.split() if tk in ("const", "restrict", "volatile")]
        rest = [tk for tk in text.split() if tk not in ("const", "restrict", "volatile")]
        rt = " ".join(rest)
        if rt in sigs and "*" in sigs[rt] and not is_fnptr_text(sigs[rt]):
            # pointer typedef: its stars add to the depth; quals here are
            # pointer-level (dropped by the caller via the returned pquals)
            inner = split_c_pointer(sigs[rt], sigs)
            return (inner[0], depth + inner[1], pquals + inner[2])
        break
    return text, depth, pquals


def _strip_typedef_chain(text, sigs):
    """Desugar a non-pointer typedef chain: xmlChar -> "unsigned char",
    xmlDoc -> "struct _xmlDoc" (stops at the first pointer/fnptr type)."""
    toks = text.split()
    quals = sorted({tk for tk in toks if tk in ("const", "restrict", "volatile")})
    rest = [tk for tk in toks if tk not in ("const", "restrict", "volatile")]
    rt = " ".join(rest)
    guard = 0
    while rt in sigs and "*" not in sigs[rt] and not is_fnptr_text(sigs[rt]) and guard < 8:
        rt = sigs[rt]
        guard += 1
    return rt, quals


def pointee_core(text, enums, sigs):
    """Canonical SOURCE token for a pointee/base text (qualifiers stripped
    and reported separately by the caller)."""
    rt, quals = _strip_typedef_chain(text, sigs)
    if rt.startswith("struct ") or rt.startswith("union ") or rt.startswith("enum "):
        core = rt
    elif rt in enums:
        core = "enum:" + rt
    else:
        core = C_BASE_NORM.get(rt, rt)
    return core + ("+" + "+".join(quals) if quals else "")


def fnptr_src(ret_text, param_texts, enums, fnptrs, sigs):
    """SOURCE fingerprint of a function-pointer type: full normalized
    signature `fn(ret)(p1,p2,...)` — a `(void*)->void` callback can no longer
    compare equal to a `(xmlNodePtr,int)->int` callback."""
    ret = c_source_fp(ret_text.strip(), enums, fnptrs, sigs) if ret_text.strip() else "void"
    ps = [c_source_fp(p, enums, fnptrs, sigs) for p in param_texts]
    return "fn(" + ret + ")(" + ",".join(ps) + ")"


def abi_eq(a, b):
    """MACHINE-ABI equality: same class/width/depth; signedness matches when
    equal OR either side is None (C enums have implementation-defined
    signedness, so an enum param binds equally well to c_int or c_uint)."""
    if a[0] != b[0] or a[1] != b[1] or a[3] != b[3]:
        return False
    if a[0] == "int":
        return a[2] == b[2] or a[2] is None or b[2] is None
    return True


def c_source_fp(t, enums, fnptrs, sigs):
    """SOURCE_PROTOTYPE_FINGERPRINT token for a C qualType."""
    t = " ".join(t.strip().split())
    if not t:
        return "other"
    # function-pointer typedef (expand to the full signature)
    if t in sigs and is_fnptr_text(sigs[t]):
        m = FNPTR_RE.match(sigs[t])
        if m:
            return fnptr_src(m.group(1), split_params(m.group(2)), enums, fnptrs, sigs)
    # inline function pointer: "RET (*)(PARAMS)" / "RET (*name)(PARAMS)"
    m = FNPTR_RE.match(t)
    if m:
        return fnptr_src(m.group(1), split_params(m.group(2)), enums, fnptrs, sigs)
    text, depth, pquals = split_c_pointer(t, sigs)
    core = pointee_core(text, enums, sigs)
    # pointer-level quals (const on a Ptr typedef, or after the last star)
    # are meaningless for a by-value parameter and ignored; pointee-level
    # const/restrict are source-visible and already folded into `core`.
    pq = "+" + "+".join(sorted(set(pquals))) if pquals else ""
    return f"{core}d{depth}{pq}"


def c_abi_fp(t, enums, fnptrs, sigs):
    """MACHINE_ABI_FINGERPRINT (class, width, signed, depth) for a C qualType."""
    t = " ".join(t.strip().split())
    if not t:
        return ("other", 0, None, 0)
    if t in sigs and is_fnptr_text(sigs[t]):
        return ("fnptr", 64, None, 0)
    if FNPTR_RE.match(t):
        return ("fnptr", 64, None, 0)
    text, depth, _pq = split_c_pointer(t, sigs)
    rt, _quals = _strip_typedef_chain(text, sigs)
    if depth > 0:
        return ("ptr", 64, None, depth)
    if rt in enums or rt.startswith("enum "):
        return ("int", 32, None, 0)
    if rt.startswith("struct ") or rt.startswith("union "):
        return ("struct", None, None, 0)
    abi = c_base_abi(rt)
    if abi is not None:
        return (abi[0], abi[1], abi[2], 0)
    return ("other", 0, None, 0)


def rust_abi_fp(t, enums, fnptrs):
    """MACHINE_ABI_FINGERPRINT (class, width, signed, depth) for a Rust type
    text. size_t ≡ usize, c_long ≡ isize ≡ long ... at the machine level."""
    t = t.strip()
    if not t:
        return ("other", 0, None, 0)
    if t == "()":
        return ("void", 0, None, 0)
    if t in ("c_int", "i32"):
        return ("int", 32, True, 0)
    if t in ("c_uint", "u32"):
        return ("int", 32, False, 0)
    if t in ("c_long", "isize", "c_longlong", "i64"):
        return ("int", 64, True, 0)
    if t in ("c_ulong", "usize", "c_ulonglong", "u64", "size_t", "ssize_t"):
        return ("int", 64, False if t in ("c_ulong", "usize", "c_ulonglong", "u64", "size_t") else True, 0)
    if t in ("c_short", "i16"):
        return ("int", 16, True, 0)
    if t in ("c_ushort", "u16"):
        return ("int", 16, False, 0)
    if t in ("c_char", "i8"):
        return ("int", 8, True, 0)
    if t in ("u8", "c_uchar"):
        return ("int", 8, False, 0)
    if t == "xmlChar":
        # typedef unsigned char (xmlstring.h)
        return ("int", 8, False, 0)
    if t in ("f32", "c_float"):
        return ("float", 32, None, 0)
    if t in ("f64", "c_double"):
        return ("float", 64, None, 0)
    if t.startswith("*mut") or t.startswith("*const"):
        depth = t.count("*")
        # `*mut xmlNodePtr` is a pointer to a pointer typedef -> depth 2
        # (upstream `xmlNode **`).
        if re.search(r"\*mut\s+\w+Ptr\b", t) or re.search(r"\*const\s+\w+Ptr\b", t):
            depth += 1
        return ("ptr", 64, None, depth)
    if t.startswith("Option<"):
        inner = t[len("Option<"):-1]
        last = inner.rsplit("::", 1)[-1]
        if ("fn" in inner and "(" in inner) or "extern" in inner or last in fnptrs:
            return ("fnptr", 64, None, 0)
        if last.endswith("Func") or last.endswith("Callback") or last.endswith("Handler"):
            return ("fnptr", 64, None, 0)
        return rust_abi_fp(inner, enums, fnptrs)
    if "fn" in t and ("(" in t or "extern" in t):
        return ("fnptr", 64, None, 0)
    if t.startswith("&"):
        return ("ptr", 64, None, 1)
    last = t.rsplit("::", 1)[-1]
    if last in fnptrs:
        return ("fnptr", 64, None, 0)
    if last.endswith("Func") or last.endswith("Function") or last.endswith("Callback"):
        return ("fnptr", 64, None, 0)
    if last in enums:
        return ("int", 32, None, 0)
    if last.endswith("Ptr"):
        return ("ptr", 64, None, 1)
    return ("other", 0, None, 0)


# ── collection ──────────────────────────────────────────────────────────────

def clang_version():
    r = subprocess.run(["clang", "--version"], capture_output=True, text=True)
    return r.stdout.splitlines()[0] if r.stdout else "unknown"


def clang_prototypes(header_dirs, include_paths, forbidden_roots, side):
    """Extract per-header FunctionDecls/TypedefDecls via clang AST dumps
    (text mode: every decl carries its true declaring file).

    Returns (decls, stats, contamination, typedefs) where typedefs is
    (enums:set, fnptrs:set, sigs:dict name->desugared qualType). All typedefs
    seen while parsing are collected (project + libc; the project uses the
    xml*/xslt*/exslt* prefixes so there is no collision), which lets the
    fingerprints canonically desugar `xmlChar`, `xmlNodePtr`, `size_t`, ...
    uniformly on both sides. FunctionDecls are kept ONLY when their declaring
    file is the parsed header itself (main-file decl-loc, or a decl-loc whose
    path resolves to the target header — the wrapper case for
    non-self-contained oracle headers, see ORACLE_HEADER_PREREQS). Resolved
    include origins are recorded via `clang -H` and checked against
    forbidden_roots (cross-universe contamination)."""
    decls = {}
    enums, fnptrs, sigs = set(), set(), {}
    stats = {"discovered": 0, "parsed": 0, "failed": []}
    contamination = []
    inc = ["-I"] + [p for path in include_paths for p in (path,)]
    for d in header_dirs:
        if not os.path.isdir(d):
            continue
        for fn in sorted(os.listdir(d)):
            if not fn.endswith(".h"):
                continue
            stats["discovered"] += 1
            path = os.path.join(d, fn)
            target_real = os.path.realpath(path)
            parse_path = path
            prereqs = ORACLE_HEADER_PREREQS.get(fn) if side == "oracle" else None
            if prereqs:
                wrapper = os.path.join(ROOT, "target", f"fsc-{side}-{fn}.c")
                os.makedirs(os.path.dirname(wrapper), exist_ok=True)
                with open(wrapper, "w") as w:
                    for p in prereqs:
                        w.write(f"#include {p}\n")
                    w.write(f'#include "{path}"\n')
                parse_path = wrapper
            r = subprocess.run(
                ["clang", "-Xclang", "-ast-dump", "-fsyntax-only", "-H"] + inc + [parse_path],
                capture_output=True, text=True)
            if r.returncode != 0:
                stats["failed"].append({"header": os.path.relpath(path, ROOT),
                                        "stderr": r.stderr[-1500:]})
                continue
            stats["parsed"] += 1
            header_text = open(path, encoding="utf-8", errors="replace").read()
            # -H include resolution log (stderr): ".... /abs/path.h"
            for line in r.stderr.splitlines():
                m = re.match(r"^\s*\.+\s+(/\S+)\s*$", line)
                if m:
                    rp = os.path.realpath(m.group(1))
                    for root in forbidden_roots:
                        if rp.startswith(root + os.sep) or rp == root:
                            contamination.append({"side": side, "header": fn,
                                                  "resolved": rp, "root": root})
            for line in r.stdout.splitlines():
                m = FD_RE.match(line)
                if m and "implicit" not in line:
                    loc_tok, name, typ = m.group(1), m.group(2), m.group(3)
                    if re.match(r"^(line|col):", loc_tok):
                        is_target = True  # declared in the parsed header itself
                    else:
                        p = loc_tok.rsplit(":", 2)[0]
                        is_target = os.path.realpath(p) == target_real
                    if not is_target:
                        continue
                    # final gate: the function name must be textually written
                    # in the target header (clang's location printing can
                    # degenerate for libc redeclarations to the main-file
                    # form; a declaration the header does not contain cannot
                    # belong to it)
                    if not re.search(r"\b" + re.escape(name) + r"\s*\x28", header_text):
                        continue
                    q = typ
                    ret = q.split("(", 1)[0].strip() if "(" in q else q
                    inner = q.split("(", 1)[1].rsplit(")", 1)[0] if "(" in q else ""
                    params = [p.strip() for p in split_params(inner)]
                    # C `(void)` is zero parameters (clang renders it as one
                    # "void" param); Rust declares `fn f()`. Normalize.
                    if params == ["void"]:
                        params = []
                    variadic = bool(re.search(r"\.\.\.", inner))
                    if name not in decls:
                        decls[name] = {"ret": ret, "params": params,
                                       "variadic": variadic, "header": fn}
                    continue
                m = TD_RE.match(line)
                if m and "implicit" not in line:
                    name, qt = m.group(1), m.group(2)
                    sigs[name] = qt
                    if qt.startswith("enum ") or " enum " in qt:
                        enums.add(name)
                    elif is_fnptr_text(qt) or "Func" in qt:
                        fnptrs.add(name)
    return decls, stats, contamination, (enums, fnptrs, sigs)


FD_RE = re.compile(
    r"^[|` ]*-FunctionDecl\s+0x[0-9a-f]+(?:\s+prev\s+0x[0-9a-f]+)?\s+"
    r"<[^>]*>\s+(\S+)\s+([A-Za-z_]\w*)\s+'(.+)'")
TD_RE = re.compile(
    r"^[|` ]*-TypedefDecl\s+0x[0-9a-f]+(?:\s+prev\s+0x[0-9a-f]+)?\s+"
    r"<[^>]*>\s+\S+\s+(?:(?:referenced|implicit)\s+)?([A-Za-z_]\w*)\s+'(.+)'")


def rust_fn_signatures():
    """Extract {name: {ret, params:[raw], variadic, path}} for every
    `extern "C" fn` in src/ (multi-line aware; const/unsafe modifiers
    allowed). Doc-comment copies are excluded by requiring the declaration
    to start a line."""
    out = {}
    pat = re.compile(
        r'(?m)^\s*(?:pub(?:\s*\([^)]*\))?\s+)?(?:(?:unsafe|const)\s+)*'
        r'extern\s+"C"\s+fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(')
    for dirpath, _dirs, files in os.walk(SRC):
        for fn in files:
            if not fn.endswith(".rs"):
                continue
            path = os.path.join(dirpath, fn)
            text = open(path, encoding="utf-8", errors="replace").read()
            for m in pat.finditer(text):
                name = m.group(1)
                i = m.end()
                depth = 1  # the matched '(' is open
                while i < len(text) and depth > 0:
                    ch = text[i]
                    if ch == "(":
                        depth += 1
                    elif ch == ")":
                        depth -= 1
                    i += 1
                params_text = text[m.end():i - 1]
                head = text[i:].split("{", 1)[0]
                variadic = bool(re.search(r'(?<!\.)\.\.\.', params_text))
                params = [rust_param_type(p) for p in split_params(params_text)]
                ret = "()"
                rm = re.search(r'->\s*([^{;]+)', head)
                if rm:
                    ret = rm.group(1).strip().rstrip()
                out[name] = {"ret": ret, "params": params,
                             "variadic": variadic,
                             "path": os.path.relpath(path, ROOT)}
    return out


def rust_param_type(p):
    """Strip the parameter name: `ctxt: *mut _xmlNode` -> `*mut _xmlNode`."""
    depth = 0
    prev = ""
    for i, ch in enumerate(p):
        if ch in "<([":
            depth += 1
        elif ch in ">)]" and not (ch == ">" and prev == "-"):
            depth -= 1
        elif ch == ":" and depth == 0:
            return p[i + 1:].strip()
        prev = ch
    return p.strip()


def macro_generated_exports():
    """Names of `extern "C" fn`s generated by export macros (not visible to
    the textual extractor): the xmlTextWriterWriteFormat* x86-64 variadic
    asm shims (vfmt_shim!) and their non-x86-64 stubs (fmt_stub!)."""
    names = set()
    text = open(os.path.join(SRC, "xml", "writer", "mod.rs"), encoding="utf-8").read()
    for m in re.finditer(r'(?m)^\s*(vfmt_shim|fmt_stub)!\s*\((.*?)\)\s*;', text, re.S):
        macro, body = m.group(1), m.group(2)
        args = split_params(body)
        if macro == "vfmt_shim":
            if args:
                names.add(args[0].strip())
        else:
            for a in args:
                names.add(a.strip())
    return names


# ── the court ──────────────────────────────────────────────────────────────

def run_court(report=False):
    findings = []
    classified = []
    compared = 0
    ok = 0

    oracle_decls, oracle_stats, oracle_contam, oracle_typedefs = clang_prototypes(
        ORACLE_HEADER_DIRS, ORACLE_INCLUDE_PATHS, ORACLE_FORBIDDEN_ROOTS, "oracle")
    cand_decls, cand_stats, cand_contam, cand_typedefs = clang_prototypes(
        CAND_HEADER_DIRS, CAND_INCLUDE_PATHS, CAND_FORBIDDEN_ROOTS, "candidate")
    cand_enums, cand_fnptrs, cand_sigs = cand_typedefs
    oracle_enums, oracle_fnptrs, oracle_sigs = oracle_typedefs

    # header parse failures are findings (fail-closed, 11.1-Z.3)
    for f in oracle_stats["failed"] + cand_stats["failed"]:
        findings.append({"symbol": "-", "plane": "header-parse",
                         "kind": "header-parse-failure",
                         "header": f["header"], "detail": f["stderr"][-1200:]})
    for c in oracle_contam + cand_contam:
        findings.append({"symbol": "-", "plane": "include-origin",
                         "kind": "include-contamination",
                         "detail": f"{c['side']} header {c['header']} resolved "
                                   f"{c['resolved']} inside forbidden root {c['root']}"})

    rust = rust_fn_signatures()
    macro_shims = macro_generated_exports()

    # ── Plane 1 vs 2: oracle headers ↔ candidate headers ─────────────────────
    for name, oc in sorted(oracle_decls.items()):
        if name in ORACLE_INTERNAL_GLOBALS:
            classified.append({"symbol": name, "plane": "oracle-vs-candidate",
                               "kind": "oracle-internal-indirection",
                               "detail": "globals.h DLL-import backing name; candidate exports the public name"})
            continue
        if name in HEADER_DECLARED_ORACLE_DSO_ABSENT:
            classified.append({"symbol": name, "plane": "oracle-vs-candidate",
                               "kind": "header-declared-oracle-dso-absent",
                               "detail": HEADER_DECLARED_ORACLE_DSO_ABSENT[name]})
            continue
        cc = cand_decls.get(name)
        if cc is None:
            findings.append({"symbol": name, "plane": "oracle-vs-candidate",
                             "kind": "missing-in-candidate-header",
                             "detail": f"oracle: {oc['ret']}({', '.join(oc['params'])}) "
                                       f"[header {oc['header']}]"})
            continue
        compared += 1
        problems = []
        # SOURCE + MACHINE fingerprints for the return type
        o_ret_src, c_ret_src = c_source_fp(oc["ret"], oracle_enums, oracle_fnptrs, oracle_sigs), \
            c_source_fp(cc["ret"], cand_enums, cand_fnptrs, cand_sigs)
        o_ret_abi, c_ret_abi = c_abi_fp(oc["ret"], oracle_enums, oracle_fnptrs, oracle_sigs), \
            c_abi_fp(cc["ret"], cand_enums, cand_fnptrs, cand_sigs)
        if o_ret_src != c_ret_src:
            problems.append(f"return SOURCE {oc['ret']}({o_ret_src}) vs {cc['ret']}({c_ret_src})")
        if not abi_eq(o_ret_abi, c_ret_abi):
            problems.append(f"return ABI {oc['ret']}({o_ret_abi}) vs {cc['ret']}({c_ret_abi})")
        if len(oc["params"]) != len(cc["params"]):
            problems.append(f"arg count oracle {len(oc['params'])} vs candidate {len(cc['params'])}")
        else:
            for i, (op, cp) in enumerate(zip(oc["params"], cc["params"])):
                o_src = c_source_fp(op, oracle_enums, oracle_fnptrs, oracle_sigs)
                c_src = c_source_fp(cp, cand_enums, cand_fnptrs, cand_sigs)
                o_abi = c_abi_fp(op, oracle_enums, oracle_fnptrs, oracle_sigs)
                c_abi = c_abi_fp(cp, cand_enums, cand_fnptrs, cand_sigs)
                if o_src != c_src:
                    problems.append(f"arg{i} SOURCE {op}({o_src}) vs {cp}({c_src})")
                if not abi_eq(o_abi, c_abi):
                    problems.append(f"arg{i} ABI {op}({o_abi}) vs {cp}({c_abi})")
        if oc["variadic"] != cc["variadic"]:
            problems.append(f"variadic oracle {oc['variadic']} vs candidate {cc['variadic']}")
        if problems:
            findings.append({"symbol": name, "plane": "oracle-vs-candidate",
                             "kind": "prototype-drift",
                             "detail": "; ".join(problems)})
        else:
            ok += 1

    # ── Plane 2 vs 3: candidate headers ↔ Rust extern signatures ─────────────
    unmeasured = []
    for name, cc in sorted(cand_decls.items()):
        if name in DATA_EXPORTS:
            classified.append({"symbol": name, "plane": "candidate-vs-rust",
                               "kind": "data-export", "detail": "DATA function-pointer/global symbol"})
            continue
        if name in ASM_SHIMS:
            classified.append({"symbol": name, "plane": "candidate-vs-rust",
                               "kind": "asm-shim",
                               "detail": "x86-64 variadic asm shim (R-000161); declared C arity is a Rust-side shim form"})
            continue
        if name in macro_shims:
            classified.append({"symbol": name, "plane": "candidate-vs-rust",
                               "kind": "generated-macro-shim",
                               "detail": "variadic asm shim generated by vfmt_shim!/fmt_stub! "
                                         "(writer/mod.rs); the fixed-arg ABI is captured from registers and "
                                         "forwarded to the measured xmlTextWriterWriteVFormat* counterpart"})
            continue
        if name.startswith(CANDIDATE_HEADER_AUXILIARY):
            classified.append({"symbol": name, "plane": "candidate-vs-rust",
                               "kind": "candidate-header-auxiliary",
                               "detail": "declared in the vendored candidate-only trio.h (the oracle 1.1.45 "
                                         "ships no trio.h); not part of the drop-in parity surface"})
            continue
        rs = rust.get(name)
        if rs is None:
            unmeasured.append(name)
            findings.append({"symbol": name, "plane": "candidate-vs-rust",
                             "kind": "candidate-decl-not-measured",
                             "detail": f"candidate header {cc['header']} declares "
                                       f"{cc['ret']}({', '.join(cc['params'])}) but no Rust extern \"C\" fn "
                                       f"is measured for it"})
            continue
        compared += 1
        problems = []
        cret = c_abi_fp(cc["ret"], cand_enums, cand_fnptrs, cand_sigs)
        rret = rust_abi_fp(rs["ret"], cand_enums, cand_fnptrs)
        if not abi_eq(cret, rret):
            problems.append(f"return ABI {cc['ret']}({cret}) vs Rust {rs['ret']}({rret})")
        if len(cc["params"]) != len(rs["params"]):
            problems.append(
                f"arg count {len(cc['params'])} ({', '.join(cc['params'])}) "
                f"vs Rust {len(rs['params'])} ({', '.join(rs['params'])})")
        else:
            for i, (cp, rp) in enumerate(zip(cc["params"], rs["params"])):
                cnorm = c_abi_fp(cp, cand_enums, cand_fnptrs, cand_sigs)
                rnorm = rust_abi_fp(rp, cand_enums, cand_fnptrs)
                if not abi_eq(cnorm, rnorm):
                    problems.append(f"arg {i} {cp}({cnorm}) vs Rust {rp}({rnorm})")
        if cc["variadic"] != rs["variadic"]:
            problems.append(f"variadic {cc['variadic']} vs Rust {rs['variadic']}")
        if problems:
            findings.append({"symbol": name, "plane": "candidate-vs-rust",
                             "kind": "signature-mismatch",
                             "detail": "; ".join(problems),
                             "rust_path": rs["path"]})
        else:
            ok += 1

    # unclassified Rust types seen in the measured set (named disposition)
    unclassified_rust = sorted({
        (rp, rs["path"]) for rs in rust.values() for rp in rs["params"]
        if rust_abi_fp(rp, cand_enums, cand_fnptrs) == ("other", 0, None, 0)
    } | {(rs["ret"], rs["path"]) for rs in rust.values()
          if rust_abi_fp(rs["ret"], cand_enums, cand_fnptrs) == ("other", 0, None, 0)})

    oracle_absent = sorted(HEADER_DECLARED_ORACLE_DSO_ABSENT)
    silent_omissions = (len(oracle_stats["failed"]) + len(cand_stats["failed"])
                        + len(unmeasured) + len(unclassified_rust))
    verdict = "FAIL" if (findings or silent_omissions > 0) else "PASS"

    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    receipt = {
        "court": "ABI-FUNCTION-SIGNATURE",
        "case": "ABI-FUNCTION-SIGNATURE-001",
        "phase": "11.1-Z.3",
        "timestamp": ts,
        "schema": "function-signature-court-2",
        "toolchain": {"clang": clang_version()},
        "planes": {
            "oracle": "system headers via clang AST (isolated include env)",
            "candidate_headers": "include/ via clang AST (isolated include env)",
            "rust": "src/ extern \"C\" fn extraction (const/unsafe aware)",
        },
        "environments": {
            "oracle_include_paths": ORACLE_INCLUDE_PATHS,
            "candidate_include_paths": CAND_INCLUDE_PATHS,
            "oracle_forbidden_roots": [os.path.relpath(r, ROOT) for r in ORACLE_FORBIDDEN_ROOTS],
            "candidate_forbidden_roots": [os.path.relpath(r, ROOT) for r in CAND_FORBIDDEN_ROOTS],
        },
        "fingerprints": {
            "source": "SOURCE_PROTOTYPE_FINGERPRINT (canonical base type, pointer depth, "
                      "pointee const/restrict, typedef identity, full fn-pointer signature, "
                      "variadic, arg count, return type, calling convention)",
            "machine": "MACHINE_ABI_FINGERPRINT (ABI class, width, signedness, pointer depth, "
                       "struct-by-value identity, callback ABI, variadic)",
        },
        "accounting": {
            "oracle_headers_discovered": oracle_stats["discovered"],
            "oracle_headers_parsed": oracle_stats["parsed"],
            "oracle_headers_failed": len(oracle_stats["failed"]),
            "candidate_headers_discovered": cand_stats["discovered"],
            "candidate_headers_parsed": cand_stats["parsed"],
            "candidate_headers_failed": len(cand_stats["failed"]),
            "oracle_fn_decls": len(oracle_decls),
            "candidate_fn_decls": len(cand_decls),
            "rust_signatures_measured": len(rust),
            "asm_shims_classified": len(ASM_SHIMS),
            "data_exports_classified": len(DATA_EXPORTS),
            "generated_macro_exports_classified": len(macro_shims),
            "candidate_header_auxiliary_classified": len([1 for n in cand_decls
                                                          if n.startswith(CANDIDATE_HEADER_AUXILIARY)]),
            "oracle_internal_globals_classified": len(ORACLE_INTERNAL_GLOBALS),
            "header_declared_oracle_dso_absent": len(oracle_absent),
            "unmeasured_functions": len(unmeasured),
            "unclassified_rust_types": len(unclassified_rust),
            "silent_omissions": silent_omissions,
        },
        "summary": {"compared": compared, "ok": ok, "findings": len(findings)},
        "classified": classified,
        "findings": findings,
        "verdict": verdict,
    }
    os.makedirs(RECEIPTS, exist_ok=True)
    rp = os.path.join(RECEIPTS, f"abi-function-signature-{ts}.json")
    with open(rp, "w") as f:
        json.dump(receipt, f, indent=1, ensure_ascii=False)
        f.write("\n")
    print(f"receipt -> {rp}")
    a = receipt["accounting"]
    print(f"oracle headers {a['oracle_headers_parsed']}/{a['oracle_headers_discovered']} parsed, "
          f"{a['oracle_headers_failed']} failed; candidate {a['candidate_headers_parsed']}/"
          f"{a['candidate_headers_discovered']} parsed, {a['candidate_headers_failed']} failed")
    print(f"fn decls oracle={a['oracle_fn_decls']} candidate={a['candidate_fn_decls']} "
          f"rust measured={a['rust_signatures_measured']}")
    print(f"compared={compared} ok={ok} findings={len(findings)} "
          f"silent_omissions={silent_omissions} verdict={verdict}")
    if report:
        for f_ in findings:
            print(f"  [{f_['kind']}] {f_['symbol']}: {f_['detail']}")
    return 0 if verdict == "PASS" else 1


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()
    return run_court(report=args.report)


if __name__ == "__main__":
    sys.exit(main())
