/**
 * @file
 *
 * Compile-time version information for libxml-rs
 */

#ifndef __XML_VERSION_H__
#define __XML_VERSION_H__

#define LIBXML_DOTTED_VERSION "2.12.0"
#define LIBXML_VERSION 21200
#define LIBXML_VERSION_STRING "21200"
#define LIBXML_VERSION_EXTRA ""

/* Feature macros — all enabled by default in libxml-rs */
#define LIBXML_THREAD_ENABLED
#define LIBXML_TREE_ENABLED
#define LIBXML_OUTPUT_ENABLED
#define LIBXML_PUSH_ENABLED
#define LIBXML_READER_ENABLED
#define LIBXML_PATTERN_ENABLED
#define LIBXML_WRITER_ENABLED
#define LIBXML_SAX1_ENABLED
#define LIBXML_VALID_ENABLED
#define LIBXML_HTML_ENABLED
#define LIBXML_C14N_ENABLED
#define LIBXML_CATALOG_ENABLED
#define LIBXML_SGML_CATALOG_ENABLED
#define LIBXML_XPATH_ENABLED
#define LIBXML_XPTR_ENABLED
#define LIBXML_XINCLUDE_ENABLED
#define LIBXML_ICONV_ENABLED
#define LIBXML_ICU_ENABLED
#define LIBXML_ISO8859X_ENABLED
#define LIBXML_DEBUG_ENABLED
#define LIBXML_REGEXP_ENABLED
#define LIBXML_AUTOMATA_ENABLED
#define LIBXML_RELAXNG_ENABLED
#define LIBXML_SCHEMAS_ENABLED
#define LIBXML_SCHEMATRON_ENABLED
#define LIBXML_MODULES_ENABLED
#define LIBXML_MODULE_EXTENSION ".so"
#define LIBXML_ZLIB_ENABLED
#define LIBXML_HTTP_STUBS_ENABLED

/* libxslt version */
#define LIBXSLT_DOTTED_VERSION "1.1.39"
#define LIBXSLT_VERSION 10139
#define LIBXSLT_VERSION_STRING "10139"
#define LIBXSLT_VERSION_EXTRA ""

#define LIBXML_TEST_VERSION xmlCheckVersion(21200);

#include <libxml/xmlexports.h>

#endif /* __XML_VERSION_H__ */
